server:
  port: 8090

spring:
 h2:
  console:
   enabled: true
   path: /h2-console
   
taco:
 orders:
  page-size: 10
  
 discount:
  codes:
   abcdef: 10

---
spring:
  profiles: prod
    
logging:
   level:
    tacos: WARN
    